### ISSUE TITLE
FAQ Link in readme is dead

### ISSUE THREAD

**Issue by nguiard** [servo/rust-fnv#26]
The link in the readme (https://www.rust-lang.org/en-US/faq.html#why-are-rusts-hashmaps-slow) gets me to a 404.

**Comment by Horki** [comment]
@SimonSapin this is fixed, can it be closed?

**Comment by omeid** [comment]
It is not fixed.

**Comment by nguiard** [comment]
@omeid The README appears to have been fixed, or did I miss something? The link I mentionned in the original issues is still dead but this link is not used anywhere in the README anymore.

**Comment by inklesspen** [comment]
The built docs (for example https://docs.rs/fnv/latest/fnv/ ) still have the broken FAQ link.
